#!/usr/bin/env bash
 
set -eu
cd "$(dirname "$0")"

PROJECT_NAME=Dev71

OUT_DIR=out
IOS_BUNDLE_DIR=${PROJECT_NAME}.app


SDK=$(xcrun --sdk iphonesimulator --show-sdk-path)


RUST_RELEASE_FLAGS=(
	"-Ccodegen-units=1"
	"-Cpanic=abort"
	"-Copt-level=z"
	"-Clto=fat"
	"-Cstrip=symbols"
	"-Cdebuginfo=0"
	"-Cdebug-assertions=false"
	"-Coverflow-checks=false"
	"-Clink-arg=-fuse-ld=/usr/bin/ld"
	"-Zlocation-detail=none"
	"-Zfmt-debug=none"
)

build_prelude() {
	echo "Compiling prelude with rustc to create a static library..."
	rustc --crate-name=prelude --crate-type=staticlib \
				--target=aarch64-apple-ios-sim \
				-v "${RUST_RELEASE_FLAGS[@]}" \
				../src/prelude/prelude.rs
	echo "Done!"
}

build_ipa() {
	echo "Compiling ios app with swiftc and creating app..."
	cp ../data/Info.plist ${IOS_BUNDLE_DIR}
	swiftc ../src/Main.swift \
  		   -target aarch64-apple-ios18.2-simulator \
  		   -sdk $SDK \
  		   -o ${IOS_BUNDLE_DIR}/$PROJECT_NAME
  echo "Done!"
}

main() {
	mkdir -p ${OUT_DIR}
	mkdir -p ${OUT_DIR}/${IOS_BUNDLE_DIR}

	cd ${OUT_DIR}
	build_prelude
	build_ipa
	cd ..
	
	echo "Build complete."
}

main
