cargo-features = ["edition2024"]

[package]
name = "dev71"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
tquic = "1.5.0"
zerocopy = { version = "0.8.10", features = ["derive"] }
