[toolchain]
channel = "1.82"
profile = "minimal"
components = [ "rustfmt", "clippy", "rust-std", "rust-analyzer" ]
targets = [ "aarch64-apple-ios", "aarch64-apple-ios-sim", "x86_64-apple-ios", "aarch64-linux-android", "armv7-linux-androideabi", "x86_64-linux-android" ]
