#ifndef _DEV71_H_
#define _DEV71_H_

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

uint32_t add(uint32_t a, uint32_t b);

#endif  /* _DEV71_H_ */
