#ifndef __OBJC__
#define CF_SWIFT_NAME(x)
#endif

#ifndef DEV71_H
#define DEV71_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually.
 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

uint32_t add(uint32_t a, uint32_t b) CF_SWIFT_NAME(add(a:b:));

#endif /* DEV71_H */
