load("@third_party//tools/cbindgen:rule.bzl", "cbindgen")

rust_library(
    name = "core71",
    srcs = ["core71/lib.rs"],
    edition = "2021",
    link_style = "static",
    visibility = ["PUBLIC"],
)

cbindgen(
    name = "core71.h",
    src = "core71/lib.rs",
    cbindgen_toml = "core71.cbindgen.toml",
    header_name = "core71",
    visibility = ["PUBLIC"],
)
